version: '2'
services:
  base-bot:
    build: ./
    volumes:
      - .:/go/src/github.com/disiqueira/MySlackBot
    environment:
      MSB_SLACKTOKEN: ${SLACK_TOKEN}
      MSB_OPENWEATHERTOKEN: ${OPEN_WEATHER_TOKEN}

  choose:
    extends: base-bot
    environment:
      APP_FUN: "choose"

  weather:
    extends: base-bot
    environment:
      APP_FUN: "weather"

